# Generated by Django 4.2.1 on 2023-05-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='choice',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('UZ', 'Uzbekistan'), ('IT', 'Italy')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
