# Generated by Django 4.2.1 on 2023-05-31 05:45

import app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mymodel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='number',
            field=models.IntegerField(validators=[app.validator.validate_even], verbose_name='number'),
        ),
    ]
